<?php

declare(strict_types=1);

namespace MirayS\Marc\CodeList;

final class Countries
{
    public const SOURCE = 'https://id.loc.gov/vocabulary/countries.json';

    public const CODES = [
        'aa' => ['name' => 'Albania', 'iso' => 'AL'],
        'abc' => ['name' => 'Alberta', 'iso' => 'CA'],
        'aca' => ['name' => 'Australian Capital Territory', 'iso' => 'AU'],
        'ae' => ['name' => 'Algeria', 'iso' => 'DZ'],
        'af' => ['name' => 'Afghanistan', 'iso' => 'AF'],
        'ag' => ['name' => 'Argentina', 'iso' => 'AR'],
        'ai' => ['name' => 'Armenia (Republic)', 'iso' => 'AM'],
        'aj' => ['name' => 'Azerbaijan', 'iso' => 'AZ'],
        'aku' => ['name' => 'Alaska', 'iso' => 'US'],
        'alu' => ['name' => 'Alabama', 'iso' => 'US'],
        'am' => ['name' => 'Anguilla', 'iso' => 'AI'],
        'an' => ['name' => 'Andorra', 'iso' => 'AD'],
        'ao' => ['name' => 'Angola', 'iso' => 'AO'],
        'aq' => ['name' => 'Antigua and Barbuda', 'iso' => 'AG'],
        'aru' => ['name' => 'Arkansas', 'iso' => 'US'],
        'as' => ['name' => 'American Samoa', 'iso' => 'AS'],
        'at' => ['name' => 'Australia', 'iso' => 'AU'],
        'au' => ['name' => 'Austria', 'iso' => 'AT'],
        'aw' => ['name' => 'Aruba', 'iso' => 'AW'],
        'ay' => ['name' => 'Antarctica', 'iso' => 'AQ'],
        'azu' => ['name' => 'Arizona', 'iso' => 'US'],
        'ba' => ['name' => 'Bahrain', 'iso' => 'BH'],
        'bb' => ['name' => 'Barbados', 'iso' => 'BB'],
        'bcc' => ['name' => 'British Columbia', 'iso' => 'CA'],
        'bd' => ['name' => 'Burundi', 'iso' => 'BI'],
        'be' => ['name' => 'Belgium', 'iso' => 'BE'],
        'bf' => ['name' => 'Bahamas', 'iso' => 'BS'],
        'bg' => ['name' => 'Bangladesh', 'iso' => 'BD'],
        'bh' => ['name' => 'Belize', 'iso' => 'BZ'],
        'bi' => ['name' => 'British Indian Ocean Territory', 'iso' => 'IO'],
        'bl' => ['name' => 'Brazil', 'iso' => 'BR'],
        'bm' => ['name' => 'Bermuda Islands', 'iso' => 'BM'],
        'bn' => ['name' => 'Bosnia and Herzegovina', 'iso' => 'BA'],
        'bo' => ['name' => 'Bolivia', 'iso' => 'BO'],
        'bp' => ['name' => 'Solomon Islands', 'iso' => 'SB'],
        'br' => ['name' => 'Burma', 'iso' => 'MM'],
        'bs' => ['name' => 'Botswana', 'iso' => 'BW'],
        'bt' => ['name' => 'Bhutan', 'iso' => 'BT'],
        'bu' => ['name' => 'Bulgaria', 'iso' => 'BG'],
        'bv' => ['name' => 'Bouvet Island', 'iso' => 'BV'],
        'bw' => ['name' => 'Belarus', 'iso' => 'BY'],
        'bx' => ['name' => 'Brunei', 'iso' => 'BN'],
        'ca' => ['name' => 'Caribbean Netherlands', 'iso' => 'BQ'],
        'cau' => ['name' => 'California', 'iso' => 'US'],
        'cb' => ['name' => 'Cambodia', 'iso' => 'KH'],
        'cc' => ['name' => 'China', 'iso' => 'CN'],
        'cd' => ['name' => 'Chad', 'iso' => 'TD'],
        'ce' => ['name' => 'Sri Lanka', 'iso' => 'LK'],
        'cf' => ['name' => 'Congo (Brazzaville)', 'iso' => 'CG'],
        'cg' => ['name' => 'Congo (Democratic Republic)', 'iso' => 'CD'],
        'ch' => ['name' => 'China (Republic : 1949- )', 'iso' => 'CN'],
        'ci' => ['name' => 'Croatia', 'iso' => 'HR'],
        'cj' => ['name' => 'Cayman Islands', 'iso' => 'KY'],
        'ck' => ['name' => 'Colombia', 'iso' => 'CO'],
        'cl' => ['name' => 'Chile', 'iso' => 'CL'],
        'cm' => ['name' => 'Cameroon', 'iso' => 'CM'],
        'co' => ['name' => 'Curaçao', 'iso' => 'CW'],
        'cou' => ['name' => 'Colorado', 'iso' => 'US'],
        'cq' => ['name' => 'Comoros', 'iso' => 'KM'],
        'cr' => ['name' => 'Costa Rica', 'iso' => 'CR'],
        'ctu' => ['name' => 'Connecticut', 'iso' => 'US'],
        'cu' => ['name' => 'Cuba', 'iso' => 'CU'],
        'cv' => ['name' => 'Cabo Verde', 'iso' => 'CV'],
        'cw' => ['name' => 'Cook Islands', 'iso' => 'CK'],
        'cx' => ['name' => 'Central African Republic', 'iso' => 'CF'],
        'cy' => ['name' => 'Cyprus', 'iso' => 'CY'],
        'dcu' => ['name' => 'District of Columbia', 'iso' => 'US'],
        'deu' => ['name' => 'Delaware', 'iso' => 'US'],
        'dk' => ['name' => 'Denmark', 'iso' => 'DK'],
        'dm' => ['name' => 'Benin', 'iso' => 'BJ'],
        'dq' => ['name' => 'Dominica', 'iso' => 'DM'],
        'dr' => ['name' => 'Dominican Republic', 'iso' => 'DO'],
        'ea' => ['name' => 'Eritrea', 'iso' => 'ER'],
        'ec' => ['name' => 'Ecuador', 'iso' => 'EC'],
        'eg' => ['name' => 'Equatorial Guinea', 'iso' => 'GQ'],
        'em' => ['name' => 'Timor-Leste', 'iso' => 'TL'],
        'enk' => ['name' => 'England', 'iso' => 'GB'],
        'er' => ['name' => 'Estonia', 'iso' => 'EE'],
        'es' => ['name' => 'El Salvador', 'iso' => 'SV'],
        'et' => ['name' => 'Ethiopia', 'iso' => 'ET'],
        'fa' => ['name' => 'Faroe Islands', 'iso' => 'FO'],
        'fg' => ['name' => 'French Guiana', 'iso' => 'GF'],
        'fi' => ['name' => 'Finland', 'iso' => 'FI'],
        'fj' => ['name' => 'Fiji', 'iso' => 'FJ'],
        'fk' => ['name' => 'Falkland Islands', 'iso' => 'FK'],
        'flu' => ['name' => 'Florida', 'iso' => 'US'],
        'fm' => ['name' => 'Micronesia (Federated States)', 'iso' => 'FM'],
        'fp' => ['name' => 'French Polynesia', 'iso' => 'PF'],
        'fr' => ['name' => 'France', 'iso' => 'FR'],
        'fs' => ['name' => 'Terres australes et antarctiques françaises', 'iso' => 'TF'],
        'ft' => ['name' => 'Djibouti', 'iso' => 'DJ'],
        'gau' => ['name' => 'Georgia', 'iso' => 'GE'],
        'gb' => ['name' => 'Kiribati', 'iso' => 'KI'],
        'gd' => ['name' => 'Grenada', 'iso' => 'GD'],
        'gg' => ['name' => 'Guernsey', 'iso' => 'GG'],
        'gh' => ['name' => 'Ghana', 'iso' => 'GH'],
        'gi' => ['name' => 'Gibraltar', 'iso' => 'GI'],
        'gl' => ['name' => 'Greenland', 'iso' => 'GL'],
        'gm' => ['name' => 'Gambia', 'iso' => 'GM'],
        'go' => ['name' => 'Gabon', 'iso' => 'GA'],
        'gp' => ['name' => 'Guadeloupe', 'iso' => 'GP'],
        'gr' => ['name' => 'Greece', 'iso' => 'GR'],
        'gs' => ['name' => 'Georgia (Republic)', 'iso' => 'GE'],
        'gt' => ['name' => 'Guatemala', 'iso' => 'GT'],
        'gu' => ['name' => 'Guam', 'iso' => 'GU'],
        'gv' => ['name' => 'Guinea', 'iso' => 'GN'],
        'gw' => ['name' => 'Germany', 'iso' => 'DE'],
        'gy' => ['name' => 'Guyana', 'iso' => 'GY'],
        'gz' => ['name' => 'Gaza Strip', 'iso' => 'PS'],
        'hiu' => ['name' => 'Hawaii', 'iso' => 'US'],
        'hm' => ['name' => 'Heard and McDonald Islands', 'iso' => 'HM'],
        'ho' => ['name' => 'Honduras', 'iso' => 'HN'],
        'ht' => ['name' => 'Haiti', 'iso' => 'HT'],
        'hu' => ['name' => 'Hungary', 'iso' => 'HU'],
        'iau' => ['name' => 'Iowa', 'iso' => 'US'],
        'ic' => ['name' => 'Iceland', 'iso' => 'IS'],
        'idu' => ['name' => 'Idaho', 'iso' => 'US'],
        'ie' => ['name' => 'Ireland', 'iso' => 'IE'],
        'ii' => ['name' => 'India', 'iso' => 'IN'],
        'ilu' => ['name' => 'Illinois', 'iso' => 'US'],
        'im' => ['name' => 'Isle of Man', 'iso' => 'IM'],
        'inu' => ['name' => 'Indiana', 'iso' => 'US'],
        'io' => ['name' => 'Indonesia', 'iso' => 'ID'],
        'iq' => ['name' => 'Iraq', 'iso' => 'IQ'],
        'ir' => ['name' => 'Iran', 'iso' => 'IR'],
        'is' => ['name' => 'Israel', 'iso' => 'IL'],
        'it' => ['name' => 'Italy', 'iso' => 'IT'],
        'iv' => ['name' => 'Côte d\'Ivoire', 'iso' => 'CI'],
        'iy' => ['name' => 'Iraq-Saudi Arabia Neutral Zone', 'iso' => NULL],
        'ja' => ['name' => 'Japan', 'iso' => 'JP'],
        'je' => ['name' => 'Jersey', 'iso' => 'JE'],
        'ji' => ['name' => 'Johnston Atoll', 'iso' => 'UM'],
        'jm' => ['name' => 'Jamaica', 'iso' => 'JM'],
        'jo' => ['name' => 'Jordan', 'iso' => 'JO'],
        'ke' => ['name' => 'Kenya', 'iso' => 'KE'],
        'kg' => ['name' => 'Kyrgyzstan', 'iso' => 'KG'],
        'kn' => ['name' => 'Korea (North)', 'iso' => 'KP'],
        'ko' => ['name' => 'Korea (South)', 'iso' => 'KR'],
        'ksu' => ['name' => 'Kansas', 'iso' => 'US'],
        'ku' => ['name' => 'Kuwait', 'iso' => 'KW'],
        'kv' => ['name' => 'Kosovo', 'iso' => 'XK'],
        'kyu' => ['name' => 'Kentucky', 'iso' => 'US'],
        'kz' => ['name' => 'Kazakhstan', 'iso' => 'KZ'],
        'lau' => ['name' => 'Louisiana', 'iso' => 'US'],
        'lb' => ['name' => 'Liberia', 'iso' => 'LR'],
        'le' => ['name' => 'Lebanon', 'iso' => 'LB'],
        'lh' => ['name' => 'Liechtenstein', 'iso' => 'LI'],
        'li' => ['name' => 'Lithuania', 'iso' => 'LT'],
        'lo' => ['name' => 'Lesotho', 'iso' => 'LS'],
        'ls' => ['name' => 'Laos', 'iso' => 'LA'],
        'lu' => ['name' => 'Luxembourg', 'iso' => 'LU'],
        'lv' => ['name' => 'Latvia', 'iso' => 'LV'],
        'ly' => ['name' => 'Libya', 'iso' => 'LY'],
        'mau' => ['name' => 'Massachusetts', 'iso' => 'US'],
        'mbc' => ['name' => 'Manitoba', 'iso' => 'CA'],
        'mc' => ['name' => 'Monaco', 'iso' => 'MC'],
        'mdu' => ['name' => 'Maryland', 'iso' => 'US'],
        'meu' => ['name' => 'Maine', 'iso' => 'US'],
        'mf' => ['name' => 'Mauritius', 'iso' => 'MU'],
        'mg' => ['name' => 'Madagascar', 'iso' => 'MG'],
        'miu' => ['name' => 'Michigan', 'iso' => 'US'],
        'mj' => ['name' => 'Montserrat', 'iso' => 'MS'],
        'mk' => ['name' => 'Oman', 'iso' => 'OM'],
        'ml' => ['name' => 'Mali', 'iso' => 'ML'],
        'mm' => ['name' => 'Malta', 'iso' => 'MT'],
        'mnu' => ['name' => 'Minnesota', 'iso' => 'US'],
        'mo' => ['name' => 'Montenegro', 'iso' => 'ME'],
        'mou' => ['name' => 'Missouri', 'iso' => 'US'],
        'mp' => ['name' => 'Mongolia', 'iso' => 'MN'],
        'mq' => ['name' => 'Martinique', 'iso' => 'MQ'],
        'mr' => ['name' => 'Morocco', 'iso' => 'MA'],
        'msu' => ['name' => 'Mississippi', 'iso' => 'US'],
        'mtu' => ['name' => 'Montana', 'iso' => 'US'],
        'mu' => ['name' => 'Mauritania', 'iso' => 'MR'],
        'mv' => ['name' => 'Moldova', 'iso' => 'MD'],
        'mw' => ['name' => 'Malawi', 'iso' => 'MW'],
        'mx' => ['name' => 'Mexico', 'iso' => 'MX'],
        'my' => ['name' => 'Malaysia', 'iso' => 'MY'],
        'mz' => ['name' => 'Mozambique', 'iso' => 'MZ'],
        'nbu' => ['name' => 'Nebraska', 'iso' => 'US'],
        'ncu' => ['name' => 'North Carolina', 'iso' => 'US'],
        'ndu' => ['name' => 'North Dakota', 'iso' => 'US'],
        'ne' => ['name' => 'Netherlands', 'iso' => 'NL'],
        'nfc' => ['name' => 'Newfoundland and Labrador', 'iso' => 'CA'],
        'ng' => ['name' => 'Niger', 'iso' => 'NE'],
        'nhu' => ['name' => 'New Hampshire', 'iso' => 'US'],
        'nik' => ['name' => 'Northern Ireland', 'iso' => 'GB'],
        'nju' => ['name' => 'New Jersey', 'iso' => 'US'],
        'nkc' => ['name' => 'New Brunswick', 'iso' => 'CA'],
        'nl' => ['name' => 'New Caledonia', 'iso' => 'NC'],
        'nmu' => ['name' => 'New Mexico', 'iso' => 'US'],
        'nn' => ['name' => 'Vanuatu', 'iso' => 'VU'],
        'no' => ['name' => 'Norway', 'iso' => 'NO'],
        'np' => ['name' => 'Nepal', 'iso' => 'NP'],
        'nq' => ['name' => 'Nicaragua', 'iso' => 'NI'],
        'nr' => ['name' => 'Nigeria', 'iso' => 'NG'],
        'nsc' => ['name' => 'Nova Scotia', 'iso' => 'CA'],
        'ntc' => ['name' => 'Northwest Territories', 'iso' => 'CA'],
        'nu' => ['name' => 'Nauru', 'iso' => 'NR'],
        'nuc' => ['name' => 'Nunavut', 'iso' => 'CA'],
        'nvu' => ['name' => 'Nevada', 'iso' => 'US'],
        'nw' => ['name' => 'Northern Mariana Islands', 'iso' => 'MP'],
        'nx' => ['name' => 'Norfolk Island', 'iso' => 'NF'],
        'nyu' => ['name' => 'New York (State)', 'iso' => 'US'],
        'nz' => ['name' => 'New Zealand', 'iso' => 'NZ'],
        'ohu' => ['name' => 'Ohio', 'iso' => 'US'],
        'oku' => ['name' => 'Oklahoma', 'iso' => 'US'],
        'onc' => ['name' => 'Ontario', 'iso' => 'CA'],
        'oru' => ['name' => 'Oregon', 'iso' => 'US'],
        'ot' => ['name' => 'Mayotte', 'iso' => 'YT'],
        'pau' => ['name' => 'Pennsylvania', 'iso' => 'US'],
        'pc' => ['name' => 'Pitcairn Island', 'iso' => 'PN'],
        'pe' => ['name' => 'Peru', 'iso' => 'PE'],
        'pf' => ['name' => 'Paracel Islands]', 'iso' => NULL],
        'pg' => ['name' => 'Guinea-Bissau', 'iso' => 'GW'],
        'ph' => ['name' => 'Philippines', 'iso' => 'PH'],
        'pic' => ['name' => 'Prince Edward Island', 'iso' => 'CA'],
        'pk' => ['name' => 'Pakistan', 'iso' => 'PK'],
        'pl' => ['name' => 'Poland', 'iso' => 'PL'],
        'pn' => ['name' => 'Panama', 'iso' => 'PA'],
        'po' => ['name' => 'Portugal', 'iso' => 'PT'],
        'pp' => ['name' => 'Papua New Guinea', 'iso' => 'PG'],
        'pr' => ['name' => 'Puerto Rico', 'iso' => 'PR'],
        'pw' => ['name' => 'Palau', 'iso' => 'PW'],
        'py' => ['name' => 'Paraguay', 'iso' => 'PY'],
        'qa' => ['name' => 'Qatar', 'iso' => 'QA'],
        'qea' => ['name' => 'Queensland', 'iso' => 'AU'],
        'quc' => ['name' => 'Québec (Province)', 'iso' => 'CA'],
        'rb' => ['name' => 'Serbia', 'iso' => 'RS'],
        're' => ['name' => 'Réunion', 'iso' => 'RE'],
        'rh' => ['name' => 'Zimbabwe', 'iso' => 'ZW'],
        'riu' => ['name' => 'Rhode Island', 'iso' => 'US'],
        'rm' => ['name' => 'Romania', 'iso' => 'RO'],
        'ru' => ['name' => 'Russia (Federation)', 'iso' => 'RU'],
        'rw' => ['name' => 'Rwanda', 'iso' => 'RW'],
        'sa' => ['name' => 'South Africa', 'iso' => 'ZA'],
        'sc' => ['name' => 'Saint-Barthélemy', 'iso' => 'BL'],
        'scu' => ['name' => 'South Carolina', 'iso' => 'US'],
        'sd' => ['name' => 'South Sudan', 'iso' => 'SS'],
        'sdu' => ['name' => 'South Dakota', 'iso' => 'US'],
        'se' => ['name' => 'Seychelles', 'iso' => 'SC'],
        'sf' => ['name' => 'Sao Tome and Principe', 'iso' => 'ST'],
        'sg' => ['name' => 'Senegal', 'iso' => 'SN'],
        'sh' => ['name' => 'Spanish North Africa', 'iso' => 'ES'],
        'si' => ['name' => 'Singapore', 'iso' => 'SG'],
        'sj' => ['name' => 'Sudan', 'iso' => 'SD'],
        'sl' => ['name' => 'Sierra Leone', 'iso' => 'SL'],
        'sm' => ['name' => 'San Marino', 'iso' => 'SM'],
        'sn' => ['name' => 'Sint Maarten', 'iso' => 'SX'],
        'snc' => ['name' => 'Saskatchewan', 'iso' => 'CA'],
        'so' => ['name' => 'Somalia', 'iso' => 'SO'],
        'sp' => ['name' => 'Spain', 'iso' => 'ES'],
        'sq' => ['name' => 'Eswatini', 'iso' => 'SZ'],
        'sr' => ['name' => 'Surinam', 'iso' => 'SR'],
        'ss' => ['name' => 'Western Sahara', 'iso' => 'EH'],
        'st' => ['name' => 'Saint-Martin', 'iso' => 'MF'],
        'stk' => ['name' => 'Scotland', 'iso' => 'GB'],
        'su' => ['name' => 'Saudi Arabia', 'iso' => 'SA'],
        'sw' => ['name' => 'Sweden', 'iso' => 'SE'],
        'sx' => ['name' => 'Namibia', 'iso' => 'NA'],
        'sy' => ['name' => 'Syria', 'iso' => 'SY'],
        'sz' => ['name' => 'Switzerland', 'iso' => 'CH'],
        'ta' => ['name' => 'Tajikistan', 'iso' => 'TJ'],
        'tc' => ['name' => 'Turks and Caicos Islands', 'iso' => 'TC'],
        'tg' => ['name' => 'Togo', 'iso' => 'TG'],
        'th' => ['name' => 'Thailand', 'iso' => 'TH'],
        'ti' => ['name' => 'Tunisia', 'iso' => 'TN'],
        'tk' => ['name' => 'Turkmenistan', 'iso' => 'TM'],
        'tl' => ['name' => 'Tokelau', 'iso' => 'TK'],
        'tma' => ['name' => 'Tasmania', 'iso' => 'AU'],
        'tnu' => ['name' => 'Tennessee', 'iso' => 'US'],
        'to' => ['name' => 'Tonga', 'iso' => 'TO'],
        'tr' => ['name' => 'Trinidad and Tobago', 'iso' => 'TT'],
        'ts' => ['name' => 'United Arab Emirates', 'iso' => 'AE'],
        'tu' => ['name' => 'Turkey', 'iso' => 'TR'],
        'tv' => ['name' => 'Tuvalu', 'iso' => 'TV'],
        'txu' => ['name' => 'Texas', 'iso' => 'US'],
        'tz' => ['name' => 'Tanzania', 'iso' => 'TZ'],
        'ua' => ['name' => 'Egypt', 'iso' => 'EG'],
        'uc' => ['name' => 'United States Misc. Caribbean Islands', 'iso' => 'UM'],
        'ug' => ['name' => 'Uganda', 'iso' => 'UG'],
        'un' => ['name' => 'Ukraine', 'iso' => 'UA'],
        'up' => ['name' => 'United States Misc. Pacific Islands', 'iso' => 'UM'],
        'utu' => ['name' => 'Utah', 'iso' => 'US'],
        'uv' => ['name' => 'Burkina Faso', 'iso' => 'BF'],
        'uy' => ['name' => 'Uruguay', 'iso' => 'UY'],
        'uz' => ['name' => 'Uzbekistan', 'iso' => 'UZ'],
        'vau' => ['name' => 'Virginia', 'iso' => 'US'],
        'vb' => ['name' => 'British Virgin Islands', 'iso' => 'VG'],
        'vc' => ['name' => 'Vatican City', 'iso' => 'VA'],
        've' => ['name' => 'Venezuela', 'iso' => 'VE'],
        'vi' => ['name' => 'Virgin Islands of the United States', 'iso' => 'VI'],
        'vm' => ['name' => 'Vietnam', 'iso' => 'VN'],
        'vp' => ['name' => 'Various places', 'iso' => NULL],
        'vra' => ['name' => 'Victoria', 'iso' => 'AU'],
        'vtu' => ['name' => 'Vermont', 'iso' => 'US'],
        'wau' => ['name' => 'Washington (State)', 'iso' => 'US'],
        'wea' => ['name' => 'Western Australia', 'iso' => 'AU'],
        'wf' => ['name' => 'Wallis and Futuna', 'iso' => 'WF'],
        'wiu' => ['name' => 'Wisconsin', 'iso' => 'US'],
        'wj' => ['name' => 'West Bank of the Jordan River', 'iso' => 'PS'],
        'wk' => ['name' => 'Wake Island', 'iso' => 'UM'],
        'wlk' => ['name' => 'Wales', 'iso' => 'GB'],
        'ws' => ['name' => 'Samoa', 'iso' => 'WS'],
        'wvu' => ['name' => 'West Virginia', 'iso' => 'US'],
        'wyu' => ['name' => 'Wyoming', 'iso' => 'US'],
        'xa' => ['name' => 'Christmas Island (Indian Ocean)', 'iso' => 'CX'],
        'xb' => ['name' => 'Cocos (Keeling) Islands', 'iso' => 'CC'],
        'xc' => ['name' => 'Maldives', 'iso' => 'MV'],
        'xd' => ['name' => 'Saint Kitts-Nevis', 'iso' => 'KN'],
        'xe' => ['name' => 'Marshall Islands', 'iso' => 'MH'],
        'xf' => ['name' => 'Midway Islands', 'iso' => 'UM'],
        'xga' => ['name' => 'Coral Sea Islands Territory', 'iso' => 'AU'],
        'xh' => ['name' => 'Niue', 'iso' => 'NU'],
        'xj' => ['name' => 'Saint Helena', 'iso' => 'SH'],
        'xk' => ['name' => 'Saint Lucia', 'iso' => 'LC'],
        'xl' => ['name' => 'Saint Pierre and Miquelon', 'iso' => 'PM'],
        'xm' => ['name' => 'Saint Vincent and the Grenadines', 'iso' => 'VC'],
        'xn' => ['name' => 'North Macedonia', 'iso' => 'MK'],
        'xna' => ['name' => 'New South Wales', 'iso' => 'AU'],
        'xo' => ['name' => 'Slovakia', 'iso' => 'SK'],
        'xoa' => ['name' => 'Northern Territory', 'iso' => 'AU'],
        'xp' => ['name' => 'Spratly Island', 'iso' => NULL],
        'xr' => ['name' => 'Czech Republic', 'iso' => 'CZ'],
        'xra' => ['name' => 'South Australia', 'iso' => 'AU'],
        'xs' => ['name' => 'South Georgia and the South Sandwich Islands', 'iso' => 'GS'],
        'xv' => ['name' => 'Slovenia', 'iso' => 'SI'],
        'xx' => ['name' => 'No place, unknown, or undetermined', 'iso' => NULL],
        'xxc' => ['name' => 'Canada', 'iso' => 'CA'],
        'xxk' => ['name' => 'United Kingdom', 'iso' => 'GB'],
        'xxu' => ['name' => 'United States', 'iso' => 'US'],
        'ye' => ['name' => 'Yemen', 'iso' => 'YE'],
        'ykc' => ['name' => 'Yukon Territory', 'iso' => 'CA'],
        'za' => ['name' => 'Zambia', 'iso' => 'ZM'],
    ];

    public static function name(string $code): ?string
    {
        return self::CODES[self::clean($code)]['name'] ?? null;
    }

    public static function iso3166(string $code): ?string
    {
        return self::CODES[self::clean($code)]['iso'] ?? null;
    }

    public static function exists(string $code): bool
    {
        return isset(self::CODES[self::clean($code)]);
    }

    private static function clean(string $code): string
    {
        return rtrim(strtolower(trim($code)));
    }
}
